In [1]:
import torch
from torch import nn

In [2]:
x = torch.randn(100, 3)
layer = nn.Linear(3, 5)
print(layer(x).shape)  # [100, 5]

print("layer.weight shape:", layer.weight.shape)
print(layer.weight)  # (5, 3)인 이유? -> 선형변환층 구조 이해가 안된다면, 노션 이론 정리 참조

# nn.Linear(in_features, out_features)는 (out_features, in_features) 크기의 weight 파라미터를 가짐.
# 즉, 입력 벡터(3차원) x에 대해 각 출력 뉴런(5개)이 모두 3개 입력에 대한 가중치를 가지고 있으므로 (5,3)
# 행렬곱: [batch, in] @ [out, in].T = [batch, out]
print("layer.bias shape:", layer.bias.shape)
print(layer.bias)

torch.Size([100, 5])
layer.weight shape: torch.Size([5, 3])
Parameter containing:
tensor([[-0.4281, -0.1837, -0.0909],
        [ 0.1981, -0.2341, -0.5403],
        [ 0.3163, -0.5156, -0.5427],
        [-0.1900,  0.1337,  0.0095],
        [-0.4197, -0.2501, -0.0199]], requires_grad=True)
layer.bias shape: torch.Size([5])
Parameter containing:
tensor([ 0.5577, -0.3168,  0.4768, -0.5166, -0.0206], requires_grad=True)


In [3]:
x=torch.randn(2,5)
layer=nn.ReLU()
print(x)
print(layer(x))

tensor([[-0.5001, -1.7196, -0.0777,  1.4349,  0.6870],
        [-0.5385, -0.8482,  0.5535,  1.1581, -0.1467]])
tensor([[0.0000, 0.0000, 0.0000, 1.4349, 0.6870],
        [0.0000, 0.0000, 0.5535, 1.1581, 0.0000]])


In [4]:
layer=nn.BatchNorm1d(3)
print(layer.weight) # 표준편차
print(layer.bias) # 평균

x = torch.randn(5,3)
print(x)
print(layer(x))
print(layer(x)[:, 2].mean())
print(layer(x).mean(dim=0))
print(layer(x).std(dim=0, unbiased=False)) # torch.std는 N-1로 나눔

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([[ 1.2979, -0.4960,  0.3500],
        [ 2.7309, -0.6796, -0.9232],
        [ 1.0310, -0.3432, -0.0353],
        [ 1.9847,  0.3811, -0.8119],
        [-0.4976, -0.5231, -0.1432]])
tensor([[-0.0106, -0.4402,  1.3719],
        [ 1.3176, -0.9333, -1.2637],
        [-0.2580, -0.0297,  0.5743],
        [ 0.6259,  1.9160, -1.0333],
        [-1.6749, -0.5128,  0.3509]], grad_fn=<NativeBatchNormBackward0>)
tensor(2.3842e-08, grad_fn=<MeanBackward0>)
tensor([-2.3842e-08,  2.3842e-08,  2.3842e-08], grad_fn=<MeanBackward1>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<StdBackward0>)


In [5]:
# nn.BatchNorm1d(3)은 입력의 feature 차원이 3개(예: [batch, 3])임을 기대함.
# 그런데 x = torch.randn(2,2)는 feature 차원이 2임. → running_mean shape mismatch 에러 발생.

layer = nn.BatchNorm1d(3)

# 올바른 입력 예시: (batch, num_features)에서 num_features=3 이어야 함
x = torch.randn(2,3)
print(x)
print(layer(x))

# 잘못된 입력(에러 예시):
# x = torch.randn(2,2)
# print(layer(x))  # RuntimeError: running_mean should contain 2 elements not 3

tensor([[ 1.0689, -1.9903, -0.9670],
        [ 0.0726,  0.1183,  0.5974]])
tensor([[ 1.0000, -1.0000, -1.0000],
        [-1.0000,  1.0000,  1.0000]], grad_fn=<NativeBatchNormBackward0>)


In [6]:
layer=nn.LayerNorm(3)
print(layer.weight) # 표준편차
print(layer.bias) # 평균

x = torch.randn(5,3)
print(x)
print(layer(x))
print(layer(x).mean(dim=1))
print(layer(x).std(dim=1, unbiased=False))

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([[-1.0153,  0.0406,  0.5297],
        [-1.4819,  0.6566, -0.2783],
        [ 0.2918, -0.3580, -2.4154],
        [-0.8086, -0.0894,  0.9479],
        [-1.5603, -1.1272, -1.4694]])
tensor([[-1.3446,  0.2930,  1.0517],
        [-1.2727,  1.1704,  0.1023],
        [ 0.9697,  0.4066, -1.3763],
        [-1.1446, -0.1471,  1.2916],
        [-0.9367,  1.3857, -0.4490]], grad_fn=<NativeLayerNormBackward0>)
tensor([0.0000e+00, 5.7121e-08, 0.0000e+00, 7.9473e-08, 9.9341e-09],
       grad_fn=<MeanBackward1>)
tensor([1.0000, 1.0000, 1.0000, 1.0000, 0.9999], grad_fn=<StdBackward0>)


In [7]:
layer=nn.BatchNorm2d(3)
print(layer.weight) # 표준편차
print(layer.bias) # 평균

x = torch.randn(5,3,32,32)
print(layer(x).mean(dim=(0,2,3)))
print(layer(x).std(dim=(0,2,3), unbiased=False))

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)
Parameter containing:
tensor([0., 0., 0.], requires_grad=True)
tensor([2.6077e-09, 1.4901e-09, 0.0000e+00], grad_fn=<MeanBackward1>)
tensor([1.0000, 1.0000, 1.0000], grad_fn=<StdBackward0>)


In [8]:
x = torch.randn(3,7)
drop = nn.Dropout(p=0.9) # 구현에서 p는 죽일 확률
print(x)
print(drop(x))
print(drop(x)*(1-0.9)) # 구현은 반대로 훈련 때 1/살릴 확률을 곱하고 테스트 때는 그대로 나오는 것으로!
drop.eval()
print(drop(x))
"""
...
nn.Linear(10,100)
nn.BatcnhNorm1d(100)
nn.ReLU()
nn.Dropout(p=0.5) 이런 식으로 구성!
...
"""

tensor([[-4.2015e-01,  2.7107e-01,  6.8595e-01, -1.8882e-03, -7.0242e-01,
          2.5672e+00, -6.0234e-03],
        [ 5.6448e-01, -1.6562e+00,  8.7374e-01,  1.9304e+00, -1.4808e+00,
          8.4941e-02,  1.7581e-01],
        [-6.5338e-01, -1.1578e+00, -3.6484e-02, -3.7880e-01, -5.4768e-01,
         -2.8494e-01,  2.9012e-02]])
tensor([[-0., 0., 0., -0., -0., 0., -0.],
        [0., -0., 0., 0., -0., 0., 0.],
        [-0., -0., -0., -0., -0., -0., 0.]])
tensor([[-0.0000,  0.0000,  0.0000, -0.0000, -0.0000,  0.0000, -0.0000],
        [ 0.0000, -0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000],
        [-0.6534, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.0000]])
tensor([[-4.2015e-01,  2.7107e-01,  6.8595e-01, -1.8882e-03, -7.0242e-01,
          2.5672e+00, -6.0234e-03],
        [ 5.6448e-01, -1.6562e+00,  8.7374e-01,  1.9304e+00, -1.4808e+00,
          8.4941e-02,  1.7581e-01],
        [-6.5338e-01, -1.1578e+00, -3.6484e-02, -3.7880e-01, -5.4768e-01,
         -2.8494e-01,  2.901

'\n...\nnn.Linear(10,100)\nnn.BatcnhNorm1d(100)\nnn.ReLU()\nnn.Dropout(p=0.5) 이런 식으로 구성!\n...\n'

In [9]:
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Linear(5,7),
                                      nn.ReLU(),
                                      nn.Dropout(p=0.9))

    def forward(self, x):
        x = self.drop_layer(x)
        return x

model=sample_model()
model.train() # train mode로 전환
x=torch.randn(3,5) # 그 담에 x=torch.randn(2,3,5)
print(model(x))

model.eval()
print(model(x)) # test mode, 일부 0인 이유는 음수인 애들이 ReLU 때문에 사라져서

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 2.2418, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 3.7702, 7.4314, 0.0000, 0.0000, 0.0000, 0.0000]],
       grad_fn=<MulBackward0>)
tensor([[1.3463, 0.7772, 0.6825, 0.0000, 0.8240, 0.0000, 0.0000],
        [0.0000, 0.2242, 0.0671, 0.4704, 0.0000, 0.1282, 0.0000],
        [0.8227, 0.3770, 0.7431, 0.0000, 0.1250, 0.0000, 0.1481]],
       grad_fn=<ReluBackward0>)


In [10]:
# 이건 내 필기용
class sample_model(nn.Module):
    def __init__(self):
        super().__init__()
        self.drop_layer=nn.Sequential(nn.Conv2d(3,3,3),
                                      nn.Dropout2d(p=0.3))
    def forward(self, x):
        x = self.drop_layer(x)
        return x

model=sample_model()
model.train()
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(DEVICE)
x=torch.randn(5,3,4,4).to(DEVICE)
model.to(DEVICE)
print(model(x))

cuda
tensor([[[[ 0.0000, -0.0000],
          [-0.0000, -0.0000]],

         [[ 0.0000, -0.0000],
          [-0.0000, -0.0000]],

         [[-1.7363,  1.1362],
          [-1.1600,  0.5760]]],


        [[[ 1.3833, -0.0535],
          [-0.2055, -2.2378]],

         [[-0.5845,  0.3978],
          [ 0.7944,  0.5716]],

         [[ 0.1446,  0.8101],
          [ 2.9247,  0.9825]]],


        [[[ 0.6309,  1.0059],
          [-0.2493, -1.1556]],

         [[-0.5734,  0.2550],
          [ 0.2549,  0.3053]],

         [[-0.2303, -0.3957],
          [-0.1722,  0.4148]]],


        [[[ 0.3554,  0.1813],
          [ 0.8215,  0.3895]],

         [[-0.3901,  0.3060],
          [-0.1344, -0.1816]],

         [[ 0.0000, -0.0000],
          [-0.0000,  0.0000]]],


        [[[-0.0000, -0.0000],
          [-0.0000,  0.0000]],

         [[ 0.9662, -1.2268],
          [-0.4029, -1.7446]],

         [[ 1.0699, -0.1999],
          [ 0.2689, -1.5253]]]], device='cuda:0', grad_fn=<MulBackward0>)


In [11]:
layer = nn.Conv2d(in_channels=1, out_channels=2, kernel_size=3) # stride=1, padding=0 이 디폴트
layer(torch.randn(32,1,5,5)).shape
# nn.Linear(3,5) # (채,채) # 근데 얘는 채 또는 개채를 원함, 개x3 => 개x5
# nn.Conv2d(3,5) # (채,채) # 근데 얘는 채행열(이미지1개) 또는 개채행열(이미지n개)을 원함, 개x3x행x열 => 개x5x행x열

torch.Size([32, 2, 3, 3])

In [12]:
# 아래는 layer = nn.Conv2d(in_channels=3, out_channels=5, kernel_size=3)와 동일 (생략 가능함)
layer = nn.Conv2d(3,5,3) # weight(=필터=커널)가 3(channel)x3x3(kernel) 짜리 5개 존재 (5x3x3x3)
print(layer(torch.randn(32,3,5,5)).shape)
print(layer.weight.shape) # 이렇게 하면 5(out)x3(in)x3(kernel)x3(kernel) 짜리 커널 생성성

torch.Size([32, 5, 3, 3])
torch.Size([5, 3, 3, 3])


In [13]:
conv1 = nn.Conv2d(1,8,6, stride=2)
x=torch.randn(32,1,28,28)
print(conv1(x).shape)

# 크기 유지 조합(커널-스트라이드-패딩) : 3-1-1 / 5-1-2 / 7-1-3 
conv2 = nn.Conv2d(8,16,3,padding=1)
print(conv2(conv1(x)).shape)

Maxpool = nn.MaxPool2d(kernel_size=2, stride=2)
print(Maxpool(conv2(conv1(x))).shape)   # Maxpooling은 채널별로 수행하므로 개채 불변

torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])


In [14]:
maxpool=nn.MaxPool2d(2) # 2 로만 줘도 자동 kernel_size=2, stride=2
x=torch.randn(1,6,6)
print(x)
print(x.shape)
print(maxpool(x))
print(maxpool(x).shape)
print(maxpool(torch.randn(32,3,6,6)).shape)

tensor([[[-0.1916, -1.2880, -1.9593, -0.0700,  0.1789,  1.0752],
         [-0.5129,  0.1094, -0.2191, -0.5466, -1.3142, -0.7072],
         [-1.0675,  0.1840,  0.6544, -1.8029,  0.0581,  0.3157],
         [ 0.5920, -1.2319, -0.3082, -0.5384, -0.5847,  0.7146],
         [-0.5534, -0.7383, -0.1695, -0.8855,  0.0648, -1.4360],
         [-0.6187,  0.3976,  0.9203,  0.3246,  0.0454,  1.0317]]])
torch.Size([1, 6, 6])
tensor([[[ 0.1094, -0.0700,  1.0752],
         [ 0.5920,  0.6544,  0.7146],
         [ 0.3976,  0.9203,  1.0317]]])
torch.Size([1, 3, 3])
torch.Size([32, 3, 3, 3])


In [15]:
maxpool=nn.AvgPool2d(2)
x=torch.randn(1,6,6)
print(x)
print(maxpool(x))
print(maxpool(torch.randn(32,3,6,6)).shape)

tensor([[[-8.2796e-02,  9.5617e-01, -4.2284e-01, -2.4106e-01, -1.9266e-01,
          -3.2561e-01],
         [ 5.3863e-01, -9.3823e-01, -1.3915e+00,  2.7392e-01, -9.4231e-01,
          -1.3173e+00],
         [-8.5910e-01, -1.3117e+00, -8.4978e-01, -1.1163e-03, -9.7646e-01,
           4.6762e-02],
         [ 5.0284e-01,  4.8959e-01, -1.8624e-01, -1.5451e+00,  8.3400e-01,
           3.3811e-01],
         [ 1.6361e+00,  1.1927e+00, -5.5450e-01, -1.5721e-01, -1.6027e+00,
          -2.4062e-01],
         [ 1.3134e+00,  1.4127e+00,  5.7445e-01, -3.0312e-03,  4.3350e-01,
          -1.4303e+00]]])
tensor([[[ 0.1184, -0.4454, -0.6945],
         [-0.2946, -0.6456,  0.0606],
         [ 1.3888, -0.0351, -0.7100]]])
torch.Size([32, 3, 3, 3])


In [16]:
class CNN(nn.Module):
    def __init__(self):
        super().__init__()

        self.conv1 = nn.Conv2d(1,8,6, stride=2)
        self.conv2 = nn.Conv2d(8,16,3, padding=1)
        self.Maxpool = nn.MaxPool2d(2)
        self.fc = nn.Linear(16*6*6,10)

    def forward(self, x):
        print(x.shape)      # 32, 1, 28, 28
        x = self.conv1(x)
        print(x.shape)      # 32, 8, 12, 12
        x = self.conv2(x)
        print(x.shape)      # 32, 16, 12, 12
        x = self.Maxpool(x)
        print(x.shape)      # 32, 16, 6, 6
        x = torch.flatten(x, start_dim=1)   # [개.채.행.렬] 중 [채.행.렬]을 flatten 하는 것이므로 start_dim=1
        print(x.shape)      # 32, 16*6*6=576
        x = self.fc(x)
        print(x.shape)      # 32, 10
        return x

x = torch.randn(32,1,28,28)
model = CNN()
print(model(x).shape)

torch.Size([32, 1, 28, 28])
torch.Size([32, 8, 12, 12])
torch.Size([32, 16, 12, 12])
torch.Size([32, 16, 6, 6])
torch.Size([32, 576])
torch.Size([32, 10])
torch.Size([32, 10])


In [17]:
# 내 필기용
rnn_cell=nn.RNN(input_size=4, hidden_size=5, batch_first=True) # activation = tanh 도 포함되어있음

x = torch.randn(3,2,4) # batch (batch_first=True 라서 맨 앞), 단어 수, 단어 하나에 대한 벡터 사이즈
out, h = rnn_cell(x)

print(out.shape) # 각 단어에 대해 h 나옴
# batch_first=True 라서 (batch, 단어 수, hidden_size) <= nn.Linear 랑 생각 방식이 똑같음
print(h.shape) # 단어 다 넣고 나서 최종 h
# (D*num_layer(bidirection 이면 D=2), batch_size, hidden_size)

Wx=rnn_cell.weight_ih_l0
Wh=rnn_cell.weight_hh_l0
bx=rnn_cell.bias_ih_l0
bh=rnn_cell.bias_hh_l0

h_init=torch.zeros(1,5)
h0=torch.tanh(x[0,0,:].unsqueeze(dim=0)@Wx.T+bx+h_init@Wh.T+bh)
h1=torch.tanh(x[0,1,:].unsqueeze(dim=0)@Wx.T+bx+h0@Wh.T+bh)
print(h0)
print(h1)

print(out)
print(h)

torch.Size([3, 2, 5])
torch.Size([1, 3, 5])
tensor([[-0.2426, -0.2167, -0.6738,  0.1831, -0.1539]],
       grad_fn=<TanhBackward0>)
tensor([[ 0.1898, -0.0531, -0.5333,  0.3317,  0.3051]],
       grad_fn=<TanhBackward0>)
tensor([[[-0.2426, -0.2167, -0.6738,  0.1831, -0.1539],
         [ 0.1898, -0.0531, -0.5333,  0.3317,  0.3051]],

        [[-0.7435, -0.0145, -0.0272,  0.2601,  0.1546],
         [-0.5982, -0.2293, -0.2389,  0.3114, -0.3793]],

        [[-0.2472, -0.3211, -0.5023,  0.1017, -0.2664],
         [-0.0273, -0.0160, -0.2734,  0.2592,  0.3488]]],
       grad_fn=<TransposeBackward1>)
tensor([[[ 0.1898, -0.0531, -0.5333,  0.3317,  0.3051],
         [-0.5982, -0.2293, -0.2389,  0.3114, -0.3793],
         [-0.0273, -0.0160, -0.2734,  0.2592,  0.3488]]],
       grad_fn=<StackBackward0>)


## .parameters() & .modules() & .children()

In [18]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Sequential(nn.Linear(2,3),
                                 nn.ReLU())
        self.fc2 = nn.Sequential(nn.Linear(3,4),
                                 nn.ReLU())
        self.fc_out = nn.Sequential(nn.Linear(4,1),
                                    nn.Sigmoid())
    def forward(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc_out(x)
        return x

model = MLP()
print(model(torch.randn(2,2)).shape)
print(model)

torch.Size([2, 1])
MLP(
  (fc1): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (fc2): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
  (fc_out): Sequential(
    (0): Linear(in_features=4, out_features=1, bias=True)
    (1): Sigmoid()
  )
)


In [19]:
model.parameters()

<generator object Module.parameters at 0x75b6541db140>

In [29]:
print(list(model.parameters())[2])
print(list(model.parameters())[2].shape)
# [layer0 weight 값, layer0 bias 값, layer1 weight 값, layer1 bias 값, ...]

Parameter containing:
tensor([[ 0.5221,  0.4005,  0.3489],
        [ 0.1783, -0.1074, -0.3849],
        [ 0.1252, -0.1595, -0.1470],
        [ 0.1959, -0.0562,  0.3641]], requires_grad=True)
torch.Size([4, 3])


In [36]:
# for tranfer learning
model = MLP()
print([p for p in model.parameters() if p.requires_grad])

for p in model.parameters(): # 전체 freeze
    p.requires_grad = False     # 전체 파라미터에 대해 학습 안하는 상태로 바꿈
model.fc_out = nn.Linear(4,10) # 새로운 레이어로 교체: 이진 분류에서 열 개 분류로!

params = [p for p in model.parameters() if p.requires_grad]
print(params)

from torch import optim
optimizer = optim.Adam(params, lr=0.1)
# params에는 requires_grad=True 인 파라미터만 들어가있고, 해당 레이어에 대해서만 최적화 진행

[Parameter containing:
tensor([[ 0.0980,  0.1803],
        [-0.2983,  0.2090],
        [ 0.2943,  0.1610]], requires_grad=True), Parameter containing:
tensor([-0.0918, -0.0532, -0.1009], requires_grad=True), Parameter containing:
tensor([[ 0.4853, -0.2550,  0.4737],
        [ 0.0446, -0.3572, -0.3172],
        [-0.0163, -0.3496,  0.0744],
        [ 0.4155,  0.4856, -0.5517]], requires_grad=True), Parameter containing:
tensor([ 0.0069,  0.2462,  0.1704, -0.5529], requires_grad=True), Parameter containing:
tensor([[-0.3309, -0.4533,  0.0010, -0.4821]], requires_grad=True), Parameter containing:
tensor([0.1383], requires_grad=True)]
[Parameter containing:
tensor([[-0.3109,  0.2022, -0.1229,  0.2312],
        [ 0.1232, -0.1715,  0.1697,  0.4298],
        [ 0.1753, -0.2300,  0.2454,  0.3314],
        [-0.2533,  0.4944,  0.1994, -0.0763],
        [-0.4344,  0.0106, -0.2461, -0.4908],
        [-0.4593, -0.2805,  0.4034,  0.0500],
        [-0.1885, -0.0285,  0.4453, -0.4559],
        [-0.0935,

In [37]:
# for tranfer learning (마지막 층은 교체, 그 전 층은 학습시키자)
model = MLP()
print([p for p in model.parameters() if p.requires_grad])

for p in list(model.parameters())[:-4]: # [마지막층 & 그 전층] 빼고 freeze
    p.requires_grad = False
model.fc_out = nn.Linear(4,10) # 이진 분류에서 열 개 분류로!

params = [p for p in model.parameters() if p.requires_grad]
print(params)

from torch import optim
optimizer = optim.Adam(params, lr=0.1)

[Parameter containing:
tensor([[-0.6116, -0.5887],
        [ 0.2113, -0.1683],
        [-0.0510,  0.2213]], requires_grad=True), Parameter containing:
tensor([ 0.5299,  0.0201, -0.3225], requires_grad=True), Parameter containing:
tensor([[ 0.5343, -0.2297, -0.1513],
        [ 0.1818, -0.0511, -0.2801],
        [-0.5713, -0.2813, -0.3389],
        [-0.2261, -0.4237, -0.5769]], requires_grad=True), Parameter containing:
tensor([-0.4598,  0.3712, -0.2304,  0.0228], requires_grad=True), Parameter containing:
tensor([[ 0.4600, -0.3023, -0.2014, -0.3923]], requires_grad=True), Parameter containing:
tensor([0.2978], requires_grad=True)]
[Parameter containing:
tensor([[ 0.5343, -0.2297, -0.1513],
        [ 0.1818, -0.0511, -0.2801],
        [-0.5713, -0.2813, -0.3389],
        [-0.2261, -0.4237, -0.5769]], requires_grad=True), Parameter containing:
tensor([-0.4598,  0.3712, -0.2304,  0.0228], requires_grad=True), Parameter containing:
tensor([[-0.2663, -0.2258,  0.0559,  0.1402],
        [ 0.4

In [38]:
list(model.named_parameters())[0]
# [('layer0.weight', weight 값), ('layer0.bias', bias 값), ('layer1.weight', weight 값), ('layer1.bias', bias 값), ...] <= 튜플 품은 리스트

('fc1.0.weight',
 Parameter containing:
 tensor([[-0.6116, -0.5887],
         [ 0.2113, -0.1683],
         [-0.0510,  0.2213]]))

In [39]:
for name, p in model.named_parameters():
    print(name)
    print(p)

fc1.0.weight
Parameter containing:
tensor([[-0.6116, -0.5887],
        [ 0.2113, -0.1683],
        [-0.0510,  0.2213]])
fc1.0.bias
Parameter containing:
tensor([ 0.5299,  0.0201, -0.3225])
fc2.0.weight
Parameter containing:
tensor([[ 0.5343, -0.2297, -0.1513],
        [ 0.1818, -0.0511, -0.2801],
        [-0.5713, -0.2813, -0.3389],
        [-0.2261, -0.4237, -0.5769]], requires_grad=True)
fc2.0.bias
Parameter containing:
tensor([-0.4598,  0.3712, -0.2304,  0.0228], requires_grad=True)
fc_out.weight
Parameter containing:
tensor([[-0.2663, -0.2258,  0.0559,  0.1402],
        [ 0.4145, -0.1262, -0.2902,  0.2950],
        [-0.4185, -0.2043, -0.3078, -0.1883],
        [-0.2807, -0.3694, -0.0356,  0.4749],
        [-0.3007, -0.3960, -0.1857,  0.0191],
        [-0.1217, -0.4635, -0.4620, -0.1026],
        [ 0.2248,  0.2389,  0.4107,  0.4616],
        [ 0.0350, -0.4022,  0.0352, -0.3927],
        [-0.2912,  0.2592,  0.4417, -0.1080],
        [-0.4316, -0.2055, -0.0501, -0.2851]], requires_gra

In [56]:
# generator는 한 번에 모든 값을 메모리에 올리지 않고, 필요한 순간마다 값을 '생성'하여 반환하는 이터레이터 객체입니다.
# 따라서 generator는 메모리 효율이 좋음
# model.modules()도 generator를 반환합니다.
model.modules()

<generator object Module.modules at 0x75b352ac3d80>

In [57]:
list(model.modules()) # generator를 list()로 감싸면 실제 값들이 리스트로 반환되어 확인할 수 있다.

[MLP(
   (fc1): Sequential(
     (0): Linear(in_features=2, out_features=3, bias=True)
     (1): ReLU()
   )
   (fc2): Sequential(
     (0): Linear(in_features=3, out_features=4, bias=True)
     (1): ReLU()
   )
   (fc_out): Linear(in_features=4, out_features=10, bias=True)
 ),
 Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=2, out_features=3, bias=True),
 ReLU(),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=3, out_features=4, bias=True),
 ReLU(),
 Linear(in_features=4, out_features=10, bias=True)]

In [44]:
print([m for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight for m in model.modules() if isinstance(m,nn.Linear)])
print([m.weight.grad for m in model.modules() if isinstance(m,nn.Linear)])

[Linear(in_features=2, out_features=3, bias=True), Linear(in_features=3, out_features=4, bias=True), Linear(in_features=4, out_features=10, bias=True)]
[Parameter containing:
tensor([[-0.6116, -0.5887],
        [ 0.2113, -0.1683],
        [-0.0510,  0.2213]]), Parameter containing:
tensor([[ 0.5343, -0.2297, -0.1513],
        [ 0.1818, -0.0511, -0.2801],
        [-0.5713, -0.2813, -0.3389],
        [-0.2261, -0.4237, -0.5769]], requires_grad=True), Parameter containing:
tensor([[-0.2663, -0.2258,  0.0559,  0.1402],
        [ 0.4145, -0.1262, -0.2902,  0.2950],
        [-0.4185, -0.2043, -0.3078, -0.1883],
        [-0.2807, -0.3694, -0.0356,  0.4749],
        [-0.3007, -0.3960, -0.1857,  0.0191],
        [-0.1217, -0.4635, -0.4620, -0.1026],
        [ 0.2248,  0.2389,  0.4107,  0.4616],
        [ 0.0350, -0.4022,  0.0352, -0.3927],
        [-0.2912,  0.2592,  0.4417, -0.1080],
        [-0.4316, -0.2055, -0.0501, -0.2851]], requires_grad=True)]
[None, None, None]


In [51]:
# weight initialization에 활용
for m in model.modules():
    if isinstance(m, nn.Linear):
        # 여기서는 언더바(kaiming_normal_)가 꼭 필요하다. 언더바가 있는 함수는 기존 weight 텐서를 제자리(in-place)에서 초기화하지만,
        # 언더바가 없는 kaiming_normal은(존재한다면) 새로운 값을 반환만 하고 실제 weight를 바꾸지 않으므로, 파라미터 업데이트가 안 된다.
        nn.init.kaiming_normal_(m.weight)
        # nn.init.constant_(m.weight, 1)

print([m.weight for m in model.modules() if isinstance(m, nn.Linear)])

[Parameter containing:
tensor([[-0.0633,  1.3881],
        [-0.2178, -1.1322],
        [ 0.0550, -0.3628]]), Parameter containing:
tensor([[-1.0456, -0.4494, -1.4130],
        [ 0.5168,  0.2558,  0.6530],
        [ 0.4579,  0.4273,  0.4054],
        [ 1.0596,  0.0271,  1.0433]], requires_grad=True), Parameter containing:
tensor([[ 0.7662, -0.9312, -0.4168,  0.1386],
        [-0.6931, -0.2125,  1.1742, -0.7435],
        [ 0.1371, -0.5200, -0.1411,  0.7198],
        [ 1.1999,  0.3388,  0.4499,  1.1127],
        [-0.0981,  0.4000,  0.3026, -0.5408],
        [ 1.0504,  0.1345,  0.8164, -0.6616],
        [-0.5533, -1.7120, -1.0131,  0.2924],
        [-0.5890,  0.2268, -0.7028,  1.2774],
        [-0.3728, -0.9618,  0.0299,  0.4292],
        [-0.5863,  0.0053, -0.0828,  1.0924]], requires_grad=True)]


In [ ]:
# model.children()는 generator(생성자)를 반환한다.
# generator란 for문 등으로 순회(iteration)할 수 있지만, 한 번에 모든 값을 메모리에 올리는 것이 아니라
# 필요할 때마다 값을 '생성'해서 반환하는 객체이다. 따라서 list()로 감싸서 실제 값들을 리스트로 확인할 수 있다.
print(model.children())        # <generator object Module.children ...>
print(list(model.children()))  # [nn.Sequential(...), nn.Sequential(...), nn.Linear(...)] 처럼 바로 하위 모듈만 출력됨 (예: sequential(linear, relu), sequential(...), ... 이런 식)

<generator object Module.children at 0x75b352ac3bc0>
[Sequential(
  (0): Linear(in_features=2, out_features=3, bias=True)
  (1): ReLU()
), Sequential(
  (0): Linear(in_features=3, out_features=4, bias=True)
  (1): ReLU()
), Linear(in_features=4, out_features=10, bias=True)]


In [61]:
list(model.children())

[Sequential(
   (0): Linear(in_features=2, out_features=3, bias=True)
   (1): ReLU()
 ),
 Sequential(
   (0): Linear(in_features=3, out_features=4, bias=True)
   (1): ReLU()
 ),
 Linear(in_features=4, out_features=10, bias=True)]

In [62]:
x = torch.randn(2,2)
list(model.children())[0](x)

tensor([[0.0000, 1.8281, 0.1946],
        [0.5402, 0.0000, 0.0000]])

In [ ]:
sub_network = nn.Sequential(*list(model.children())[:2])
print(sub_network)
sub_network(x)

Sequential(
  (0): Sequential(
    (0): Linear(in_features=2, out_features=3, bias=True)
    (1): ReLU()
  )
  (1): Sequential(
    (0): Linear(in_features=3, out_features=4, bias=True)
    (1): ReLU()
  )
)


tensor([[0.1144, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.0000, 0.0000, 1.3539]], grad_fn=<ReluBackward0>)

In [ ]:
# 내 필기용
# def get_activation(name):
#     def hook(model, input, output):
#         activation[name] = output.detach()
#     return hook

# model.fcs1.register_forward_hook(get_activation('fcs1'))

## Sequential vs ModuleList

In [ ]:
fc=nn.Linear(3,3)
layer_list = [fc for _ in range(5)]   # 이렇게 하면 layer_list는 fc라는 "하나의 동일한 객체"가 5번 참조되어 들어가게 됨 (모두 같은 Linear 레이어를 가리킴)
layers1 = nn.Sequential(*layer_list)  # *(unpacking)은 리스트의 각 원소를 각각의 인자로 풀어서 전달한다. nn.Sequential(layer_list)로 하면 "하나의 리스트"가 하나의 모듈로 들어가지만, nn.Sequential(*layer_list)는 리스트의 각 모듈이 순서대로 들어가 순차적으로 쌓여서 올바르게 동작한다.
layers2 = nn.ModuleList(layer_list)
print(layers1)
print(layers2)

x=torch.randn(1,3)
print(layers1(x))

# print(layers2(x)) # error!
for layer in layers2:
    x = layer(x)
print(x)

Sequential(
  (0): Linear(in_features=3, out_features=3, bias=True)
  (1): Linear(in_features=3, out_features=3, bias=True)
  (2): Linear(in_features=3, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=3, bias=True)
  (4): Linear(in_features=3, out_features=3, bias=True)
)
ModuleList(
  (0-4): 5 x Linear(in_features=3, out_features=3, bias=True)
)
tensor([[0.3293, 0.1672, 0.2470]], grad_fn=<AddmmBackward0>)
tensor([[0.3293, 0.1672, 0.2470]], grad_fn=<AddmmBackward0>)


In [65]:
# 그럼 nn.Sequential 쓰고 말지 왜 굳이 nn.ModuleList?
class small_block(nn.Module):
    def __init__(self):
        super().__init__()
        self.block_x = nn.Linear(1,1)
        self.block_y = nn.Linear(1,1)

    def forward(self, x, y):
        x = self.block_x(x)
        y = self.block_y(y)
        return x, y

model = nn.Sequential(small_block(),
                      small_block())
# model(torch.randn(1), torch.randn(1)) # error!
# nn.Sequential 이 가지고 있는 forward 함수를 call 하기 때문에 입력을 두 개 넣으면 안 된다!!
# nn.Sequential 이 가지고 있는 forward 함수는 기본적으로 입력을 하나만 받도록 설계되어 있어서(self까지 포함하면 2개),
# model(torch.randn(1), torch.randn(1))처럼 괄호 안에 2개를 넣었는데,
# 파이썬 내부적으로는 self(=model 인스턴스) + torch.randn(1) + torch.randn(1) 이렇게 총 3개의 인자가 전달된다.
# 즉, 실제로 forward(self, input, ...)의 self까지 포함해서 인자를 계산해서 "3 were given"이라고 나온다.

model = nn.ModuleList([small_block(),
                       small_block()])
x = torch.randn(1)
y = torch.randn(1)
for block in model:
    x, y = block(x,y)
print(x, y)

tensor([0.7407], grad_fn=<ViewBackward0>) tensor([0.5802], grad_fn=<ViewBackward0>)


In [ ]:
# 걍 리스트 쓰지 왜 nn.ModuleList 를 쓸까?
class testNet(nn.Module):
    def __init__(self):
        super().__init__()

        # self.Module_List = [nn.Linear(3,3), nn.Linear(3,3)]
        self.Module_List = nn.ModuleList([nn.Linear(3,3), nn.Linear(3,3)])

    def forward(self,x):
        for layer in self.Module_List:
            x = layer(x)
        return x

model=testNet()
print(model(torch.randn(1,3))) # 통과까진 문제 없음

print(model) # 그냥 리스트로 하니 아무것도 등록이 안 돼 있다!

optimizer = optim.Adam(model.parameters(), lr = 0.1) # 등록이 안 돼 있으면 parameter를 못 찾는다!

tensor([[-0.1564,  0.2218, -0.1784]], grad_fn=<AddmmBackward0>)
testNet(
  (Module_List): ModuleList(
    (0-1): 2 x Linear(in_features=3, out_features=3, bias=True)
  )
)


In [ ]:
# next(load_model.parameters()).is_cuda # 내 필기용: 모델이 gpu에 올라갔나 확인

# Transposed convolution (내 필기용)

In [ ]:
import torch
from torch import nn

up = nn.ConvTranspose2d(1, 1, kernel_size=3, stride=3, padding=0, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3],[1,2,3],[1,2,3]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) # Conv2d는 corr이지만 ConvTranspose2d 는 conv다!

up = nn.ConvTranspose2d(1, 1, kernel_size=3, stride=2, padding=0, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3],[1,2,3],[1,2,3]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) # Conv2d는 corr이지만 ConvTranspose2d 는 conv다!

tensor([[[1., 2., 3., 2., 4., 6.],
         [1., 2., 3., 2., 4., 6.],
         [1., 2., 3., 2., 4., 6.],
         [1., 2., 3., 2., 4., 6.],
         [1., 2., 3., 2., 4., 6.],
         [1., 2., 3., 2., 4., 6.]]])
tensor([[[ 1.,  2.,  5.,  4.,  6.],
         [ 1.,  2.,  5.,  4.,  6.],
         [ 2.,  4., 10.,  8., 12.],
         [ 1.,  2.,  5.,  4.,  6.],
         [ 1.,  2.,  5.,  4.,  6.]]])


## kernel_size 및 padding에 따라

In [ ]:
up = nn.ConvTranspose2d(1, 1, kernel_size=5, stride=2, padding=0, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) # 벌리는건 stride에 의해, zero padding은 kernel_size에 의해 결정

up = nn.ConvTranspose2d(1, 1, kernel_size=4, stride=2, padding=0, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) # kernel_size가 짝수면? 사실 padding이이 위왼쪽에 두줄인지 오른쪽 아래에 두줄인지는 중요하지 않음. 결과는 같다!

up = nn.ConvTranspose2d(1, 1, kernel_size=5, stride=2, padding=2, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) # padding option은 output에서 지우기

tensor([[[ 1.,  2.,  5.,  8., 11.,  8., 10.],
         [ 1.,  2.,  5.,  8., 11.,  8., 10.],
         [ 2.,  4., 10., 16., 22., 16., 20.],
         [ 2.,  4., 10., 16., 22., 16., 20.],
         [ 2.,  4., 10., 16., 22., 16., 20.],
         [ 1.,  2.,  5.,  8., 11.,  8., 10.],
         [ 1.,  2.,  5.,  8., 11.,  8., 10.]]])
tensor([[[ 1.,  2.,  5.,  8.,  6.,  8.],
         [ 1.,  2.,  5.,  8.,  6.,  8.],
         [ 2.,  4., 10., 16., 12., 16.],
         [ 2.,  4., 10., 16., 12., 16.],
         [ 1.,  2.,  5.,  8.,  6.,  8.],
         [ 1.,  2.,  5.,  8.,  6.,  8.]]])
tensor([[[10., 16., 22.],
         [10., 16., 22.],
         [10., 16., 22.]]])


## output_padding에 따라

In [ ]:
up = nn.ConvTranspose2d(1, 1, kernel_size=5, stride=2, padding=0, output_padding=0, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) #

up = nn.ConvTranspose2d(1, 1, kernel_size=5, stride=5, padding=0, output_padding=2, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) #

tensor([[[ 1.,  2.,  5.,  8., 11.,  8., 10.],
         [ 1.,  2.,  5.,  8., 11.,  8., 10.],
         [ 2.,  4., 10., 16., 22., 16., 20.],
         [ 2.,  4., 10., 16., 22., 16., 20.],
         [ 2.,  4., 10., 16., 22., 16., 20.],
         [ 1.,  2.,  5.,  8., 11.,  8., 10.],
         [ 1.,  2.,  5.,  8., 11.,  8., 10.]]])
tensor([[[ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2.,  4.,  6.,  8., 10.,  0.,  0.],
         [ 1.,  2.,  3.,  4.,  5.,  2

In [ ]:
up = nn.ConvTranspose2d(1, 1, 4, stride=2, padding=0, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) # kernel_size가 짝수면? 사실 padding이이 위왼쪽에 두줄인지 오른쪽 아래에 두줄인지는 중요하지 않음. 결과는 같다!

up = nn.ConvTranspose2d(1, 1, 4, stride=2, padding=2, output_padding=1, bias=False)
up.weight.requires_grad=False
up.weight.data = torch.tensor([[[[1.,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]]]])
x = torch.tensor([[[1.,2],[1,2]]])
print(up(x)) # kernel_size가 짝수면? 사실 padding이이 위왼쪽에 두줄인지 오른쪽 아래에 두줄인지는 중요하지 않음. 결과는 같다!

tensor([[[ 1.,  2.,  5.,  8.,  6.,  8.],
         [ 1.,  2.,  5.,  8.,  6.,  8.],
         [ 2.,  4., 10., 16., 12., 16.],
         [ 2.,  4., 10., 16., 12., 16.],
         [ 1.,  2.,  5.,  8.,  6.,  8.],
         [ 1.,  2.,  5.,  8.,  6.,  8.]]])
tensor([[[10., 16., 12.],
         [10., 16., 12.],
         [ 5.,  8.,  6.]]])


## 채널이 한 개가 아니고 여러 개면?

In [ ]:
up = nn.ConvTranspose2d(2, 1, kernel_size=2, stride=2, bias=False)
up.weight.data[0] = torch.tensor([[[1.,1],[1,1]]])
up.weight.data[1] = torch.tensor([[[2.,2],[2,2]]])
print(up.weight.shape)
print(up.weight.data)
x = torch.tensor([ [[1.,1],[0,0]], [[1.,0],[1,0]] ])
print(up(x)) # 채널 여러개? 도장 찍고 더하는 원리는 동일!

torch.Size([2, 1, 2, 2])
tensor([[[[1., 1.],
          [1., 1.]]],


        [[[2., 2.],
          [2., 2.]]]])
tensor([[[3., 3., 1., 1.],
         [3., 3., 1., 1.],
         [2., 2., 0., 0.],
         [2., 2., 0., 0.]]], grad_fn=<SqueezeBackward1>)


## Grouped convolution (내 필기용)

In [ ]:
print(nn.Conv2d(128, 256, 3, groups=32).weight.shape)
# 입력 들어온 128을 32그룹으로 쪼개서 봄 -> 그래서 각 그룹이 한 채널을 만들면 128 -> 32가 됨
# 따라서, 32의 배수가 돼야 함. 128 -> 256 이면 weight shape은 32*8, 4, 3, 3 으로 concat 해놓음
print(nn.Conv2d(128, 256, 3, groups=32).weight.shape)
print(nn.Conv2d(128, 256, 3, groups=1).weight.shape)
# 그냥 conv에 비해 weight 개수가 32배 줄어드는 효과!

torch.Size([256, 4, 3, 3])
torch.Size([256, 4, 3, 3])
torch.Size([256, 128, 3, 3])


In [ ]:
# print(nn.Conv2d(128, 33, 3, groups=32).weight.shape) # ValueError: out_channels must be divisible by groups

## DepSep conv (내 필기용)

In [ ]:
print(nn.Conv2d(3,16,3).weight.numel())
print(nn.Conv2d(3,3,3,groups=3).weight.numel())
print(nn.Conv2d(3,16,1).weight.numel())

432
27
48


In [ ]:
# # 내 필기용 : DeepAIday 강의자료에 쓸 사진
# import torch
# import torch.nn.functional as F
# input = torch.tensor([[[[1,2,2],[1,2,2],[2,3,3]]]])
# filter1 = torch.tensor([[[[-1,1],[-1,1]]]])
# filter2 = torch.tensor([[[[-1,-1],[1,1]]]])
# filter3 = torch.tensor([[[[0,1],[1,0]]]])

# print(input.shape)
# print(filter1.shape)
# print(F.conv2d(input,filter1))
# print(F.conv2d(input,filter2))
# print(F.conv2d(input,filter3))

# filters = torch.randn(1,1, 2, 2)
# inputs = torch.randn(1,1, 3, 3)
# F.conv2d(inputs, filters)


# input = torch.tensor([[[[1,1,2,2,2],[1,1,2,2,2],[1,1,2,2,2],[1,1,2,2,2],[1,1,2,2,2]]]])
# filter = torch.tensor([[[[-1,0,1],[-1,0,1],[-1,0,1]]]])
# print(F.conv2d(input,filter))
# print(F.conv2d(input,filter,padding=1))
# print(F.conv2d(input,filter,stride=2))

In [ ]:
# # 내 필기용 : DeepAIday 강의자료에 쓸 사진
# import torch
# import torch.nn.functional as F
# import matplotlib.pyplot as plt
# from google.colab import drive
# drive.mount('/content/drive')

# image=plt.imread("/content/drive/MyDrive/Colab Notebooks/picture/village.PNG")
# im_torch=torch.tensor(image[...,0:3]).permute(2,0,1).unsqueeze(0)
# print(im_torch.shape)

# filter1 = torch.tensor([[ [[-1.,0,1],[-1,0,1],[-1,0,1]] for _ in range(3)]])
# filter2 = torch.tensor([[ [[-1.,-1,-1],[0,0,0],[1,1,1]] for _ in range(3)]])
# filter3 = torch.ones(3,1,5,5)

# im1=F.conv2d(im_torch,filter1, padding=1)
# im2=F.conv2d(im_torch,filter2, padding=1)
# im3=F.conv2d(im_torch,filter3, padding=1, groups=3) # depth-wise convolution
# # print(nn.Conv2d(3,3,3, groups=3).weight.shape)

# plt.figure(figsize=(40,15))
# image_plot=im_torch.squeeze().permute(1,2,0).numpy()
# print(image_plot.shape)
# plt.imshow(image_plot)
# plt.colorbar()
# plt.xticks([])
# plt.yticks([])

# plt.figure(figsize=(40,15))
# plt.imshow(abs(im1.squeeze()), cmap="gray_r")
# plt.colorbar()
# plt.xticks([])
# plt.yticks([])

# plt.figure(figsize=(40,15))
# plt.imshow(abs(im2.squeeze()), cmap="gray_r")
# plt.colorbar()
# plt.xticks([])
# plt.yticks([])

# plt.figure(figsize=(40,15))
# plt.imshow(abs(im3.squeeze().permute(1,2,0)/25), cmap="gray_r")
# plt.colorbar()
# plt.xticks([])
# plt.yticks([])

## RNN test

In [ ]:
import torch
from torch import nn

rnn = nn.RNN(input_size=4, hidden_size=3, num_layers=1, bias=False, batch_first=True)
x = torch.randn(2, 3, 4) # 개단차
h0 = torch.randn(1, 2, 3) # (direction*num_layers, 개, hidden_size) <- batch_first=True 여도
output, ht = rnn(x, h0)

Wx = rnn.weight_ih_l0         # shape (hidden_size, input_size)
Wh = rnn.weight_hh_l0         # shape (hidden_size, hidden_size)

h_prev = h0[0]
output_manual = []
for t in range(x.shape[1]):
    xt = x[:, t, :]
    ht_manual = torch.tanh(xt @ Wx.T + h_prev @ Wh.T)
    output_manual.append(ht_manual)
    h_prev = ht_manual

output_manual = torch.stack(output_manual, dim=1)       # 개단차

print(output.shape)
print(output_manual.shape)
print(output)
print(output_manual)

print(ht[0].shape)
print(ht_manual.shape)
print(ht[0]) # 마지막 h가 담겨있음
print(ht_manual)

torch.Size([2, 3, 3])
torch.Size([2, 3, 3])
tensor([[[ 0.7393,  0.5391, -0.3272],
         [-0.5528,  0.7916, -0.1096],
         [ 0.3939,  0.3733, -0.9349]],

        [[ 0.1908,  0.3145, -0.2411],
         [ 0.4920, -0.2683, -0.3451],
         [-0.3893, -0.1180,  0.8619]]], grad_fn=<TransposeBackward1>)
tensor([[[ 0.7393,  0.5391, -0.3272],
         [-0.5528,  0.7916, -0.1096],
         [ 0.3939,  0.3733, -0.9349]],

        [[ 0.1908,  0.3145, -0.2411],
         [ 0.4920, -0.2683, -0.3451],
         [-0.3893, -0.1180,  0.8619]]], grad_fn=<StackBackward0>)
torch.Size([2, 3])
torch.Size([2, 3])
tensor([[ 0.3939,  0.3733, -0.9349],
        [-0.3893, -0.1180,  0.8619]], grad_fn=<SelectBackward0>)
tensor([[ 0.3939,  0.3733, -0.9349],
        [-0.3893, -0.1180,  0.8619]], grad_fn=<TanhBackward0>)
